In [79]:
import pandas as pd

In [80]:
df = pd.read_csv("Car_data_set.csv")

In [81]:
df.head()

,Unnamed: 0,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,manufacturing_year,mileage(kmpl),engine(cc),max_power(bhp),torque(Nm),price(in lakhs)
0,0,2017 Mercedes-Benz S-Class S400,Jul-17,Comprehensive,Petrol,5,56000,First Owner,Automatic,2017,7.81,2996.0,2996.0,333.0,63.75
1,1,2020 Nissan Magnite Turbo CVT XV Premium Opt BSVI,Jan-21,Comprehensive,Petrol,5,30615,First Owner,Automatic,2020,17.40,999.0,999.0,9863.0,8.99
2,2,2018 BMW X1 sDrive 20d xLine,Sep-18,Comprehensive,Diesel,5,24000,First Owner,Automatic,2018,20.68,1995.0,1995.0,188.0,23.75
3,3,2019 Kia Seltos GTX Plus,Dec-19,Comprehensive,Petrol,5,18378,First Owner,Manual,2019,16.50,1353.0,1353.0,13808.0,13.56
4,4,2019 Skoda Superb LK 1.8 TSI AT,Aug-19,Comprehensive,Petrol,5,44900,First Owner,Automatic,2019,14.67,1798.0,1798.0,17746.0,24.00

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1499 entries, 0 to 1498
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          1499 non-null   int64
 1   car_name            1499 non-null   object
 2   registration_year   1499 non-null   object
 3   insurance_validity  1499 non-null   object
 4   fuel_type           1499 non-null   object
 5   seats               1499 non-null   int64
 6   kms_driven          1499 non-null   int64
 7   ownsership          1499 non-null   object
 8   transmission        1499 non-null   object
 9   manufacturing_year  1499 non-null   int64
 10  mileage(kmpl)       1499 non-null   float64
 11  engine(cc)          1499 non-null   float64
 12  max_power(bhp)      1499 non-null   float64
 13  torque(Nm)          1499 non-null   float64
 14  price(in lakhs)     1499 non-null   float64
dtypes: float64(5), int64(4), object(6)
memory usage: 175.8+ KB

In [83]:
print(df['insurance_validity'].value_counts())

insurance_validity
Comprehensive            1081
Third Party insurance     289
Zero Dep                   64
Third Party                63
Not Available               2
Name: count, dtype: int64

In [84]:
df['insurance_validity'] = df['insurance_validity'].map({
    'Comprehensive': 0,
    'Zero Dep': 1,
    'Third Party': 3,
    'Third Party insurance': 2,
    'Not Available': 4
})

In [85]:
print(df['insurance_validity'].value_counts())

insurance_validity
0    1081
2     289
1      64
3      63
4       2
Name: count, dtype: int64

In [86]:
df.rename(columns={'ownsership': 'ownership'}, inplace=True)

In [87]:
print(df['ownership'].value_counts())

ownership
First Owner     1236
Second Owner     240
Third Owner       21
Fifth Owner        2
Name: count, dtype: int64

In [88]:
df['ownership'] = df['ownership'].map({
    'First Owner': 1,
    'Second Owner': 2,
    'Third Owner': 3,
    # 'Fourth Owner': 4, 
    'Fifth Owner': 5
})

In [89]:
print(df['ownership'].value_counts())

ownership
1    1236
2     240
3      21
5       2
Name: count, dtype: int64

In [90]:
print(df['fuel_type'].value_counts())

fuel_type
Petrol    997
Diesel    480
CNG        22
Name: count, dtype: int64

In [91]:
df['fuel_type'] = df['fuel_type'].map({
    'Petrol': 0,
    'Diesel': 1,
    'CNG': 2
})

In [92]:
print(df['fuel_type'].value_counts())

fuel_type
0    997
1    480
2     22
Name: count, dtype: int64

In [93]:
print(df['registration_year'].value_counts())

registration_year
Jul-18    38
Jul-17    29
Aug-18    29
May-17    26
Oct-18    25
          ..
Feb-13     1
Nov-09     1
Apr-13     1
Nov-11     1
Sep-12     1
Name: count, Length: 175, dtype: int64

In [94]:
df['registration_year'] = df['registration_year'].str.split('-').str[1]

In [49]:
print(df['registration_year'].head())

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: registration_year, dtype: float64

In [50]:
df.head()

,Unnamed: 0,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownership,transmission,manufacturing_year,mileage(kmpl),engine(cc),max_power(bhp),torque(Nm),price(in lakhs)
0,0,2017 Mercedes-Benz S-Class S400,NaN,0,NaN,5,56000,NaN,1,2017,7.81,2996.0,2996.0,333.0,63.75
1,1,2020 Nissan Magnite Turbo CVT XV Premium Opt BSVI,NaN,0,NaN,5,30615,NaN,1,2020,17.40,999.0,999.0,9863.0,8.99
2,2,2018 BMW X1 sDrive 20d xLine,NaN,0,NaN,5,24000,NaN,1,2018,20.68,1995.0,1995.0,188.0,23.75
3,3,2019 Kia Seltos GTX Plus,NaN,0,NaN,5,18378,NaN,0,2019,16.50,1353.0,1353.0,13808.0,13.56
4,4,2019 Skoda Superb LK 1.8 TSI AT,NaN,0,NaN,5,44900,NaN,1,2019,14.67,1798.0,1798.0,17746.0,24.00

In [95]:
print(df['transmission'].value_counts())

transmission
Manual       832
Automatic    667
Name: count, dtype: int64

In [96]:
df['transmission'] = df['transmission'].map({
    'Manual': 0,
    'Automatic': 1
})

In [97]:
print(df['transmission'].value_counts())

transmission
0    832
1    667
Name: count, dtype: int64

In [98]:
df.head()

,Unnamed: 0,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownership,transmission,manufacturing_year,mileage(kmpl),engine(cc),max_power(bhp),torque(Nm),price(in lakhs)
0,0,2017 Mercedes-Benz S-Class S400,17,0,0,5,56000,1,1,2017,7.81,2996.0,2996.0,333.0,63.75
1,1,2020 Nissan Magnite Turbo CVT XV Premium Opt BSVI,21,0,0,5,30615,1,1,2020,17.40,999.0,999.0,9863.0,8.99
2,2,2018 BMW X1 sDrive 20d xLine,18,0,1,5,24000,1,1,2018,20.68,1995.0,1995.0,188.0,23.75
3,3,2019 Kia Seltos GTX Plus,19,0,0,5,18378,1,0,2019,16.50,1353.0,1353.0,13808.0,13.56
4,4,2019 Skoda Superb LK 1.8 TSI AT,19,0,0,5,44900,1,1,2019,14.67,1798.0,1798.0,17746.0,24.00

In [99]:
print(df.columns)

Index(['Unnamed: 0', 'car_name', 'registration_year', 'insurance_validity',
       'fuel_type', 'seats', 'kms_driven', 'ownership', 'transmission',
       'manufacturing_year', 'mileage(kmpl)', 'engine(cc)', 'max_power(bhp)',
       'torque(Nm)', 'price(in lakhs)'],
      dtype='object')

In [100]:
X = df[['insurance_validity', 'ownership', 'fuel_type', 'kms_driven', 'transmission']]
Y = df['price(in lakhs)']

In [101]:
# # print(X)
# print(Y)

In [102]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR

In [106]:
models = { 'LinReg': LinearRegression(),
           'KNN-3':KNeighborsRegressor(n_neighbors=3),
           'SVM-Poly':SVR(kernel='poly')}
for name, model in models.items():
    model.fit(X,Y)
    sc = model.score(X,Y)
    print(name,sc)

LinReg 0.01933928258008355
KNN-3 0.5927591859141721
SVM-Poly -0.002159340262247289

In [110]:
final_model = models['KNN-3']

In [112]:
insurance_validity = input('insurance_validity')
ownership = input('ownership')
fuel_type =input('fuel_type')
kms_driven = input('kms_driven')
transmission = input('transmission')

insurance_validity Zero Dep
ownership First Owner
fuel_type petrol
kms_driven 200000
transmission Automatic

In [113]:
final_model = models['KNN-3']

In [114]:
d1 = {'Comprehensive': 0,'Zero Dep': 1,'Third Party': 3,'Third Party insurance': 2,'Not Available': 4}
d2 = {'First Owner': 1,'Second Owner': 2,'Third Owner': 3,'Fourth Owner': 4, 'Fifth Owner': 5}
d3 = {'Petrol': 0,'Diesel': 1,'CNG': 2}
d4 = {'Manual': 0,'Automatic': 1}

In [116]:
insurance_validity = input('insurance_validity')
ownership = input('ownership')
fuel_type =input('fuel_type')
kms_driven = input('kms_driven')
transmission = input('transmission')
insurance_validity = d1[insurance_validity]
ownership = d2[ownership]
fuel_type = d3[fuel_type]
kms_driven = int(kms_driven)
transmission  = d4[transmission]
test = [[insurance_validity, ownership, fuel_type, kms_driven, transmission]]
yp = int(final_model.predict(test)[0])
print('Pridicted value is: {} Rs'.format(yp))

insurance_validity Zero Dep
ownership First Owner
fuel_type CNG
kms_driven 100000
transmission Automatic

Pridicted value is: 18

C:\Users\omkar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(

In [118]:
import pickle 
pickle.dump(final_model, open('Final_model.pkl', 'wb'))# ram object is converted into the Hard disk model where we can access the model anytime anywhere